pool:
  vmImage: "ubuntu-16.04"

stages:

- stage: setup
  displayName: Compile PixelOven packages
  jobs:
  - job: setup
    strategy:
      matrix:
        node_10_x:
          node_version: 10.x
    steps:
    - task: NodeTool@0 
      inputs:
        versionSpec: $(node_version)
    - script: yarn install

- stage: compile-pixeloven
  displayName: Compile PixelOven packages
  jobs:
  - job: compile 
    steps:
    - script: yarn pixeloven:compile

- stage: check-pixeloven
  displayName: Check quality of PixelOven packages
  jobs:
  - job: lint 
    steps:
    - script: yarn pixeloven:lint
  - job: test 
    steps:
    - script: yarn pixeloven:test

- stage: build-pixeloven
  displayName: Build PixelOven apps
  jobs:
  - job: build 
    steps:
    - script: yarn pixeloven:build

