stages:
- stage: Development
  jobs:
  - job: Build
    pool:
      vmImage: "ubuntu-16.04"
    strategy:
      matrix:
        node_10_x:
          node_version: 10.x
        node_12_x:
          node_version: 12.x
    steps:
    - task: NodeTool@0 
      inputs:
        versionSpec: $(node_version)
    - script: npm i -g npm
      displayName: Update npm
    - script: curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
      displayName: Update yarn
    - script: npm i -g lerna
      displayName: Install lerna
    - script: lerna bootstrap
      displayName: Bootstrap dependencies
    - script: yarn pixeloven:compile
      displayName: Compile PixelOven packages
    - script: yarn pixeloven:lint
      displayName: Lint PixelOven packages
    - script: yarn pixeloven:test
      displayName: Test PixelOven packages
    - script: yarn pixeloven:build:production
      displayName: Build PixelOven apps
    - script: yarn pixeloven:report:coverage
      displayName: Report PixelOven code coverage
    # Run against examples now -- eventually this should be setup as a true integration step
    - script: yarn examples:compile
      displayName: Compile Example packages
    - script: yarn examples:lint
      displayName: Lint Example packages
    - script: yarn examples:test
      displayName: Test Example packages
    - script: yarn examples:build:production
      displayName: Build Example apps
    - script: yarn examples:report:coverage
      displayName: Report Example code coverage