pool:
  vmImage: "ubuntu-16.04"

stages:
- stage: Setup
  jobs:
  - job: Setup
    strategy:
      matrix:
        node_10_x:
          node_version: 10.x
    steps:
    - task: NodeTool@0 
      inputs:
        versionSpec: $(node_version)
    - script: yarn install
- stage: compile-pixeloven
  - displayName: Compile PixelOven packages
  - job: compile 
    - script: yarn pixeloven:compile
- stage: check-pixeloven
  - displayName: Check quality of PixelOven packages
  - job: lint 
    - script: yarn pixeloven:lint
  - job: test 
    - script: yarn pixeloven:test
- stage: build-pixeloven
  - displayName: Build PixelOven apps
  - job: build 
    - script: yarn pixeloven:build

