pool:
  vmImage: "ubuntu-16.04"
strategy:
  matrix:
    node_10_x:
      node_version: 10.x

stages:
- stage: Setup
  jobs:
  - job: Setup
    steps:
    - task: NodeTool@0 
      inputs:
        versionSpec: $(node_version)
    - script: yarn all:bootstrap
# - stage: Test
#   jobs:
#   - job: TestOnWindows
#     steps:
#     - script: echo Testing on Windows!
#   - job: TestOnLinux
#     steps:
#     - script: echo Testing on Linux!
# - stage: Deploy
#   jobs:
#   - job: Deploy
#     steps:
#     - script: echo Deploying the code!
