stages:
- stage: Development
  jobs:
  - job: PixelOven
    pool:
      vmImage: "ubuntu-16.04"
    strategy:
      matrix:
        node_10_x:
          node_version: 10.x
        # Comment out until we can figure out how to not report coverage twice
        # node_12_x:
        #   node_version: 12.x
    steps:
    - task: NodeTool@0 
      inputs:
        versionSpec: $(node_version)
    # Setup
    - script: npm i -g npm
      displayName: Update npm
    - script: curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
      displayName: Update yarn
    - script: npm i -g lerna
      displayName: Install lerna
    - script: lerna bootstrap
      displayName: Bootstrap dependencies
    # CLI Pipeline
    - script: yarn all:compile
      displayName: Compile PixelOven packages
    - script: yarn all:lint
      displayName: Lint PixelOven packages
    - script: yarn all:test
      displayName: Test PixelOven packages
    # Site Pipeline
    - script: yarn all:build
      displayName: Build PixelOven Site
    # Reporting
    - script: yarn codecov -t $(CODECOV_TOKEN)
      displayName: Report code coverage
    # @todo Run against examples now
    # @todo Create an integration test suite
