# Overrides for production: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
version: '3'
services:  
  react-ssr-example:
    # command: "pm2 start --no-daemon ./dist/server.js"
    command: "node ./dist/server.js"
    environment:
      BABEL_ENV: production
      ENVIRONMENT: production
      NODE_ENV: production
