# Overrides for development: docker-compose up
version: '3'
volumes:
  node_modules:
services:  
  react-ssr-example:
    build:
      context: .
    command: "yarn start"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    environment:
      BABEL_ENV: development
      ENVIRONMENT: development
      NODE_ENV: development
      TSC_WATCHFILE: UseFsEventsWithFallbackDynamicPolling
