# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

# Reusable commands
commands:
  setup:
    steps:
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
            - "apps/**/**/node_modules"
            - "packages/**/**/node_modules"
  compile:
    description: "Compiling"
    parameters:
      type:
        type: string
    steps:
      - run:
          name: Compile source
          command: yarn << parameters.type >>:compile
  document:
    description: "Documenting"
    parameters:
      type:
        type: string
    steps:
      - run:
          name: Documenting source
          command: yarn << parameters.type >>:document
  lint:
    description: "Linting"
    parameters:
      type:
        type: string
    steps:
      - run:
          name: Linting source
          command: yarn << parameters.type >>:lint
  test:
    description: "Testing"
    parameters:
      type:
        type: string
    steps:
      - run:
          name: Test source
          command: yarn << parameters.type >>:test:ci
  list:
    description: "List directory contents"
    parameters:
      path:
        type: string
        default: "."
    steps:
      - run:
          name: "List Directory"
          command: ls -al << parameters.path >>
  report-coverage:
    description: "Reporting coverage"
    parameters:
      type:
        type: string
    steps:
      - run:
          name: Reporting coverage for << parameters.type >>
          command: yarn << parameters.type >>:report:coverage
executors:
  node-executor:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/pixeloven
jobs:
  setup:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - checkout
      - setup
      - persist_to_workspace:
          root: .
          paths: 
            .
  compile-packages:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - compile:
          type: "packages"
      - persist_to_workspace:
          root: .
          paths: 
            .
  lint-packages:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - lint:
          type: "packages"
  test-packages:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - test:
          type: "packages"
  document-packages:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - document:
          type: "packages"
  accept-packages:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - list:
          path: packages/**/**
  report-packages:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - list:
          path: packages/**/**/coverage/lcov.info
      - report-coverage:
          type: "packages"
  lint-apps:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - lint:
          type: "apps"
  test-apps:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - test:
          type: "apps"
  document-apps:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - document:
          type: "apps"
  build-apps:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - run:
          name: Build source
          command: yarn apps:build
  accept-apps:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - list:
          path: apps/**/**
  report-apps:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - list:
          path: apps/**/**/coverage/lcov.info
      - report-coverage:
          type: "apps"
workflows:
  version: 2.1
  runner:
    jobs:
      - setup:
          filters:
            branches:
              ignore: gh-pages
      - compile-packages:
          requires:
            - setup
      - document-packages:
          requires:
            - compile-packages
      - lint-packages:
          requires:
            - compile-packages
# EXITING BECAUSE OF MEM????
      # - test-packages:
      #     requires:
      #       - compile-packages
      - accept-packages:
          requires:
            - document-packages
            - lint-packages
            # - test-packages
      - report-packages:
          requires:
            - accept-packages
          filters:
            branches:
              only: master
      - document-apps:
          requires:
            - accept-packages
      - lint-apps:
          requires:
            - accept-packages
      - test-apps:
          requires:
            - accept-packages
      - build-apps:
          requires:
            - document-apps
            - lint-apps
            - test-apps
      - report-apps:
          requires:
            - build-apps
          filters:
            branches:
              only: master
