# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

# Reusable commands
commands:
  compile:
    description: "Compiling"
    parameters:
      type:
        type: string
    steps:
      - run:
          name: Compile source
          command: yarn << parameters.type >>:compile
      - persist_to_workspace:
          root: .
          paths: 
            - << parameters.type >>/**/dist
  document:
    description: "Documenting"
    parameters:
      type:
        type: string
    steps:
      - run:
          name: Documenting source
          command: yarn << parameters.type >>:document
      - persist_to_workspace:
          root: .
          paths: 
            - << parameters.type >>/**/docs
  lint:
    description: "Linting"
    parameters:
      type:
        type: string
    steps:
      - run:
          name: Linting source
          command: yarn << parameters.type >>:lint
  test:
    description: "Testing"
    parameters:
      type:
        type: string
    steps:
      - run:
          name: Test source
          command: yarn << parameters.type >>:test
      - persist_to_workspace:
          root: .
          paths: 
            - << parameters.type >>/**/coverage
  list:
    description: "List directory contents"
    parameters:
      path:
        type: string
        default: "."
    steps:
      - run:
          name: "List Directory"
          command: ls -al << parameters.path >>
executors:
  node-executor:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/pixeloven
jobs:
  # @todo Need to rethink this cache mechanism. Even if cache works we still need to do yarn install????
  # @todo How can we split the build for packages and applications?
  setup:
    executor: node-executor
    steps:
      # @todo We should create a custom docker image with lerna installed or find a way to add lerna to the executor
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node-v1-{{ .Branch }}-
            - node-v1-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: node-v1-{{ checksum "yarn.lock" }}
          paths:
            - "./node_modules"
      - persist_to_workspace:
          root: .
          paths: 
            - .
  compile-examples:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - compile:
          type: "examples"
  compile-packages:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - compile:
          type: "packages"
  lint-examples:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - lint:
          type: "examples"
  lint-packages:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - lint:
          type: "packages"
  test-examples:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - test:
          type: "examples"

  test-packages:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - test:
          type: "packages"
  build-examples:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - run:
          name: Build source
          command: yarn examples:build
      - persist_to_workspace:
          root: .
          paths: 
            - examples/**/dist
  document-examples:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - document:
          type: "examples"
  document-packages:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - document:
          type: "packages"
  accept-examples:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - list:
          path: examples/**/dist
      - store_artifacts:
          path: examples/**/dist
          destination: examples/dist
      - list:
          path: examples/**/coverage
      - store_artifacts:
          path: examples/**/coverage
          destination: examples/coverage
      - list:
          path: examples/**/docs
      - store_artifacts:
          path: examples/**/docs
          destination: examples/docs
  accept-packages:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - list:
          path: packages/**/dist
      - store_artifacts:
          path: packages/**/dist
          destination: packages/dist
      - list:
          path: packages/**/coverage
      - store_artifacts:
          path: packages/**/coverage
          destination: packages/coverage
      - list:
          path: packages/**/docs
      - store_artifacts:
          path: packages/**/docs
          destination: packages/docs
      - run:
          name: "Linking"
          command: yarn all:linker
  report:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven

      # Check for coverage files for reporting
      - list:
          path: examples/**/coverage/lcov.info
      - list:
          path: packages/**/coverage/lcov.info

      # Run test and report
      - run:
          name: Report source
          command: yarn all:report:coverage
  deploy:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/pixeloven
      - list:
          path: .
      # @todo generate docs and run newly compiled tool to deploy to github pages
      # doc gen might be it's own job though

      # @todo need to do this https://github.com/atlassian/lerna-semantic-release
      # @todo would be nice to also deploy the above to a special branch for github
      # https://blog.frederikring.com/articles/deploying-github-pages-circle-ci/
      # should add the typedocs as well.

workflows:
  version: 2.1
  runner:
    jobs:
      - setup:
          filters:
            branches:
              ignore: gh-pages
      - compile-packages:
          requires:
            - setup
      - document-packages:
          requires:
            - compile-packages
      - lint-packages:
          requires:
            - compile-packages
      - test-packages:
          requires:
            - compile-packages
      - accept-packages:
          requires:
            - compile-packages
            - document-packages
            - lint-packages
            - test-packages
      - build-examples:
          requires:
            - accept-packages
      - compile-examples:
          requires:
            - accept-packages
      - document-examples:
          requires:
            - accept-packages
      - lint-examples:
          requires:
            - accept-packages
      - test-examples:
          requires:
            - accept-packages
      - accept-examples:
          requires:
            - build-examples
            - compile-examples
            - document-examples
            - lint-examples
            - test-examples
      - report:
          requires:
            - accept-packages
            - accept-examples
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - accept-packages
            - accept-examples
          filters:
            branches:
              only: master
